# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('travelStart', models.DateTimeField()),
                ('travelEnd', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wished_items',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='wisher',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.AddField(
            model_name='travel',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_travel', to='wl.User'),
        ),
        migrations.AddField(
            model_name='grouptravel',
            name='joiner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_list', to='wl.Travel'),
        ),
        migrations.AddField(
            model_name='grouptravel',
            name='traveler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wished_travel', to='wl.User'),
        ),
    ]
