# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-28 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wl', '0002_auto_20171128_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='plan',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
